name: actions1 on issue comment

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  printMessage:
    runs-on: ubuntu-latest

    steps:
    - name: print message
      run: echo "An issue commant is added! Triggered by $GITHUB_ACTOR"
